apiVersion: v2
name: minecraft-operator-crds
description: Custom Resource Definitions for Minecraft Operator
type: application
version: 0.4.0
appVersion: "0.4.0"
keywords:
  - minecraft
  - operator
  - kubernetes
  - crds
maintainers:
  - name: lexfrei
    email: f@lex.la
    url: https://github.com/lexfrei
kubeVersion: ">=1.27.0-0"
