apiVersion: v2
name: minecraft-operator-crds
description: Custom Resource Definitions for Minecraft Operator
type: application
version: 0.3.0
appVersion: "0.3.0"
keywords:
  - minecraft
  - operator
  - kubernetes
  - crds
maintainers:
  - name: Aleksei Sviridkin
    email: f@lex.la
kubeVersion: ">=1.27.0-0"
