apiVersion: v2
name: minecraft-operator
description: Kubernetes operator for managing PaperMC Minecraft servers
type: application
version: 0.0.0-dev
appVersion: "0.0.0-dev"
keywords:
  - minecraft
  - papermc
  - operator
  - kubernetes
maintainers:
  - name: lexfrei
    email: f@lex.la
    url: https://github.com/lexfrei
kubeVersion: ">=1.27.0-0"
dependencies:
  - name: minecraft-operator-crds
    version: "0.0.0-dev"
    repository: "file://../minecraft-operator-crds"
    condition: crds.enabled
