image:
  tag: v0.4.4
webui:
  httproute:
    enabled: true
    parentRefs:
      - name: cilium-gateway-internal
        namespace: kube-system
        sectionName: https-home-lex-la
    hostnames:
      - mco.home.lex.la
