# This rule is not used by the project minecraft-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the mc.k8s.lex.la.mc.k8s.lex.la.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: minecraft-operator
    app.kubernetes.io/managed-by: kustomize
  name: papermcserver-editor-role
rules:
- apiGroups:
  - mc.k8s.lex.la.mc.k8s.lex.la
  resources:
  - papermcservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mc.k8s.lex.la.mc.k8s.lex.la
  resources:
  - papermcservers/status
  verbs:
  - get
