# This rule is not used by the project minecraft-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over mc.k8s.lex.la.mc.k8s.lex.la.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: minecraft-operator
    app.kubernetes.io/managed-by: kustomize
  name: plugin-admin-role
rules:
- apiGroups:
  - mc.k8s.lex.la.mc.k8s.lex.la
  resources:
  - plugins
  verbs:
  - '*'
- apiGroups:
  - mc.k8s.lex.la.mc.k8s.lex.la
  resources:
  - plugins/status
  verbs:
  - get
