apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "minecraft-operator.fullname" . }}-leader-election-binding
  labels:
    {{- include "minecraft-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "minecraft-operator.fullname" . }}-leader-election
subjects:
- kind: ServiceAccount
  name: {{ include "minecraft-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
