{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "minecraft-operator.fullname" . }}-controller-manager-metrics-service
  labels:
    control-plane: controller-manager
    {{- include "minecraft-operator.labels" . | nindent 4 }}
spec:
  ports:
  - name: https
    port: {{ .Values.metrics.port }}
    protocol: TCP
    targetPort: metrics
  selector:
    control-plane: controller-manager
    {{- include "minecraft-operator.selectorLabels" . | nindent 4 }}
{{- end }}
