apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "minecraft-operator.fullname" . }}-controller-manager
  labels:
    {{- include "minecraft-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
