{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "minecraft-operator.fullname" . }}-webhook
  labels:
    app.kubernetes.io/component: webhook
    {{- include "minecraft-operator.labels" . | nindent 4 }}
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: webhook
  selector:
    control-plane: controller-manager
    {{- include "minecraft-operator.selectorLabels" . | nindent 4 }}
{{- end }}
